# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r

after_failure:
  - ./travis-tool.sh dump_logs

env:
  - BOOTSTRAP_LATEX=1
  - WARNINGS_ARE_ERRORS=1

notifications:
  email:
    on_success: change
    on_failure: change
